name: "Composer package action"
description: "With this GitHub Action, you can build a package for the PHP Composer package manager."
inputs:
  directory:
    description: "The name of the directory for package building"
    default: ".build"
  file:
    description: "The name of the built package file"
    default: "package.zip"
outputs:
  directory:
    description: 'The path to the building directory'
  path:
    description: 'The path to the compiled package archive'
runs:
  using: "docker"
  image: "action.Dockerfile"
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.file }}
branding:
  icon: 'package'
  color: 'purple'
