name: "Composer package build"
description: "Composer package build from repository using GitHub Actions"
inputs:
  BUILD_DIRECTORY_NAME:
    description: "build directory name"
    default: ".build"
  BUILD_FILE_NAME:
    description: "package file name"
    default: "package.zip"
outputs:
  directory:
    description: 'The path to the building directory'
  path:
    description: 'The path to the compiled package archive'
runs:
  using: "docker"
  image: "action.Dockerfile"
  args:
    - ${{ inputs.BUILD_DIRECTORY_NAME }}
    - ${{ inputs.BUILD_FILE_NAME }}
