services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    environment:
      directory: ${directory}
      file: ${file}
    volumes:
      - .:/usr/bin/app
