name: tests

on:
  pull_request: ~
  push:
    branches: ['*.*.x', 'master']

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH}}

      - run: cp .env.ci .env

      - uses: falti/dotenv-action@master
        id: dotenv

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            PHP_VERSION=${{ steps.dotenv.outputs.PHP_VERSION }}
          push: false
