name: tests

on:
  pull_request: ~
  push:
    branches: ['*.*.x']

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH}}
      - run: cp .env.dist .env
      - uses: falti/dotenv-action@master
        id: dotenv
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            PHP_VERSION=${{ steps.dotenv.outputs.PHP_VERSION }}
          push: false
  composer-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 8.3
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - run: composer validate --strict --ansi
#  check-require:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        php:
#          - 8.3
#    steps:
#      - uses: actions/checkout@v4
#      - uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#          tools: composer:v2
#          coverage: none
#      - uses: ramsey/composer-install@v2
#        with:
#          composer-options: --optimize-autoloader
#      - run: composer require-checker
